package openNeo.old.test;

import openNeo.old.SpawnEggTabel;

import java.util.ArrayList;
import java.util.List;

public class SpawnEggTest {
    public static void main(String[] args) {
        List<String> mobs = new ArrayList<>();
        mobs.add("cow");
        mobs.add("chicken");
        mobs.add("pig");
        mobs.add("sheep");
        mobs.add("wolf");
        mobs.add("mushroomcow");
        mobs.add("creeper");
        mobs.add("enderman");
        mobs.add("silverfish");
        mobs.add("skeleton");
        mobs.add("slime");
        mobs.add("spider");
        mobs.add("zombie");
        mobs.add("pigzombie");
        mobs.add("villager");
        mobs.add("squid");
        mobs.add("ocelot");
        mobs.add("witch");
        mobs.add("bat");
        mobs.add("ghast");
        mobs.add("lava_slime");
        mobs.add("blaze");
        mobs.add("cave_spider");
        mobs.add("horse");
        mobs.add("rabbit");
        mobs.add("endermite");
        mobs.add("guardian");
        mobs.add("stray");
        mobs.add("husk");
        mobs.add("wither_skeleton");
        mobs.add("donkey");
        mobs.add("mule");
        mobs.add("skeletonhorse");
        mobs.add("zombiehorse");
        mobs.add("shulker");
        mobs.add("elderguardian");
        mobs.add("polarbear");
        mobs.add("llama");
        mobs.add("vindicator");
        mobs.add("evoker");
        mobs.add("vex");
        mobs.add("zombievillager");
        mobs.add("parrot");
        mobs.add("clownfish");
        mobs.add("cod");
        mobs.add("pufferfish");
        mobs.add("salmon");
        mobs.add("drowned");
        mobs.add("dolphin");
        mobs.add("turtle");
        mobs.add("phantom");
        mobs.add("agent");
        mobs.add("cat");
        mobs.add("panda");
        mobs.add("fox");
        mobs.add("pillager");
        mobs.add("ravager");
        mobs.add("mask");
        mobs.add("zoglin");
        mobs.add("hoglin");
        mobs.add("warden");
        mobs.add("trader_llama");
        mobs.add("tadpole");
        mobs.add("strider");
        mobs.add("piglin_brute");
        mobs.add("piglin");
        mobs.add("axolotl");
        mobs.add("allay");
        mobs.add("frog");
        mobs.add("goat");
        mobs.add("glow_squid");
        mobs.add("camel");
        mobs.add("iron_golem");
        mobs.add("snow_golem");
        mobs.add("wither");
        mobs.add("ender_dragon");
        mobs.add("polarbear");
        mobs.add("sniffer");
        mobs.add("bee");
        mobs.add("wandering_trader");
        mobs.add("breeze");
        mobs.add("armadillo");
        mobs.add("bogged");

        SpawnEggTabel spawnEggTabel = new SpawnEggTabel();
        spawnEggTabel.add(mobs);
        spawnEggTabel.generate();
        spawnEggTabel.save();
    }
}